// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ComputePSTD
NumericVector ComputePSTD(NumericVector vectorM1, NumericVector vectorM2);
RcppExport SEXP _PSTD_ComputePSTD(SEXP vectorM1SEXP, SEXP vectorM2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vectorM1(vectorM1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vectorM2(vectorM2SEXP);
    rcpp_result_gen = Rcpp::wrap(ComputePSTD(vectorM1, vectorM2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PSTD_ComputePSTD", (DL_FUNC) &_PSTD_ComputePSTD, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PSTD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
