# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' ComputeDistancesPSTD
#' @description
#' Function to compute the probabililistic distance between two gene tree probabilities for the Hellinger (dH, first), KL (dKL, second), and JS (dJS, third) distance measures of Garba et al 2018
#' 
#' IMPORTANT: This function assumes that the two gene tree probability vectors (vectorM1 and vectorM2) are sorted by to be the same. That is, the first gene tree in vectorM1 is also the first gene tree in vectorM2, and so on...
#' The gene tree probability output files of HYBRID-COAL are sorted automatically.
#' 
#' @param vectorM1 Vector of the gene tree probabilities for M1
#' 
#' @param vectorM2 Vector of the gene tree probabilities for M2
#' 
#' @examples 
#' 
#' vector.GeneTreeProbs.M1 <- Read.GeneTree.Probabilities(string.PathToGeneTreeProbs = '~/Desktop/EXAMPLE/SmallTree/M1.prob')
#' vector.GeneTreeProbs.M2 <- Read.GeneTree.Probabilities(string.PathToGeneTreeProbs = '~/Desktop/EXAMPLE/SmallTree/M2.prob')
#' 
#' ComputePSTD(vectorM1 = vector.GeneTreeProbs.M1, vectorM2 = vector.GeneTreeProbs.M2)
#' 
#' @details
#' \code{ComputeDistancesPSTD} Computes the probabilistic distances between two probability distributions
#' @export
ComputePSTD <- function(vectorM1, vectorM2) {
    .Call('_PSTD_ComputePSTD', PACKAGE = 'PSTDistanceR', vectorM1, vectorM2)
}

